### ISSUE TITLE
A cross-origin error was thrown after `npm start`

### ISSUE THREAD

**Issue by calvingit** [EllisMin/gatsby-minimalistic-dmin#2]
There was an error after running npm start:

> Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://fb.me/react-crossorigin-error for more information.
> ▶ 12 stack frames were collapsed.
> (anonymous function)
> /Volumes/HDD/Projects/gatsby-minimalistic-dmin/.cache/app.js:67
> ```javascript
>   64 | const preferDefault = m => (m && m.default) || m
>   65 | let Root = preferDefault(require(`./root`))
>   66 | domReady(() => {
> > 67 |   renderer(<Root />, rootElement, () => {
>   68 |     apiRunner(`onInitialClientRender`)
>   69 |   })
>   70 | })
> ```
> View compiled
> This screen is visible only in development. It will not appear if the app crashes in production.
> Open your browser’s developer console to further inspect this error.

Why? Did I miss anything?

**Comment by EllisMin** [comment]
I apologize for the late response. Would you please try running in terminal either `npm run clean` or `gatsby clean` then restart with `npm start`?

**Comment by EllisMin** [comment]
I apologize for the late response.

Would you please try `npm run clean` (equivalent to `gatsby clean`), then try again with `npm start`?

**Comment by EllisMin** [comment]
I apologize for the late response.

Would you please try running in terminal npm run clean (equivalent to gatsby clean), then try again with npm start?

gatsby clean wipes out the .cache folder

**Comment by EllisMin** [comment]
I apologize for the late response.

Would you please try running in terminal `npm run clean` (equivalent to `gatsby clean`), then try again with `npm start`?

`gatsby clean` wipes out the `.cache` folder

**Comment by calvingit** [comment]
I tried `gatsby clean`, it's not working in Chrome. But it's OK in Firefox and Safari.

**Comment by EllisMin** [comment]
Could you try hard refreshing your chrome browser? (Ctrl + Shirt + R or Command + Shirt + R on Mac). It will clear the browser's cache

**Comment by calvingit** [comment]
It's not working too. But if opened with Incognito Mode, it's OK. That's strange.

**Comment by EllisMin** [comment]
Hmm sounds like a cache issue to me.

You can navigate to `chrome://settings/` (in URL), then try `Clear browser data` located under Privacy and security

**Comment by calvingit** [comment]
After `Clear browser data` , and restart Chrome, the cross-origin error is gone.
